name: Delete Current Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  delete_release_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Get release ID
        id: get_release_id
        run: |
          echo "::set-output name=release_id::${{ github.event.release.id }}"

      - name: List release assets
        id: list_release_assets
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release_id.outputs.release_id }}/assets" | jq -r '.[].id' > assets.txt

      - name: Delete release assets
        run: |
          while read asset_id; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
          done < assets.txt
