name: Delete Published Release Assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  delete_release_assets:
    runs-on: ubuntu-latest

    steps:
      - name: List release assets
        id: list_release_assets
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets" | jq -r '.[] | select(.state == "uploaded") | .id' | xargs -I {} curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/assets/{}"
